### PR TITLE
Add support for paginated results

### PR DESCRIPTION
**Pull request by ramesius**
Pretty much implements the same logic found in hammertime to follow paginated results returned from the AWS `describeImages` api. Solves #2

### CODE REVIEW

**Review by willfalconer — CHANGES_REQUESTED** [review]
Needs a unit test for handling pagination

**Comment by ramesius** [comment]
Added a test for pagination. It was a tad tricky, but it checks that paginated results are followed by confirming that `describeImages` is called multiple times when a nextToken is present, as well as making sure that the `nextToken` is passed as params to following requests.

**Review by willfalconer — APPROVED** [review]
Looking good. nice one.

**Comment by willfalconer** [comment]
@ramesius Are you right to merge this PR?

**Comment by ramesius** [comment]
Done @willfalconer :+1: Thanks for the poke, had almost forgotten about this :smile:

**Comment by willfalconer** [comment]
Now just need to get nib to start using this version. @ramesius

**Pull request merged**
